sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tPzxkh7kvcW7xhopETE
    access-key-secret: ddgd2xlh6kaMLzvFFOnsaON914DjE2
    bucket-name: sky-take-out272